name: Deploy to Unikraft Cloud

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  UKC_TOKEN: ${{ secrets.UKC_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5

      - name: Install Unikraft CLI
        uses: unikraft/setup-action@main

      - name: Login
        run: echo $UKC_TOKEN | unikraft login --token -

      - name: Build & push image
        run: unikraft build . --output kaceygarman/my-node-app:latest

      - name: Remove old instance if exists
        continue-on-error: true
        run: unikraft instance rm -f my-node-app || true

      - name: Deploy instance
        run: |
          unikraft run --metro fra \
            --name my-node-app \
            -p 443:8080/http+tls \
            -m 512M \
            --scale-to-zero policy=on,cooldown-time=5000,stateful=true \
            --image kaceygarman/my-node-app:latest
